
    <?php include('partials/header.php'); ?>

    
    <div class="table">
        <div class="table__content">
            <h1 class="table__content-title list-title">The Basics Of Breeding Rabbits</h1>
        </div>
        <div class="table__container">
            <p>Before we begin to discuss breeding rabbits, it is important to understand that there are several reasons NOT to breed your rabbits.  Some of these are good reasons, but some reasons aren’t good at all.  If you are a beginning rabbit owner, or have rabbits as pets only, there are a lot more justifications for NOT breeding your rabbit than to go ahead with it!  One major consideration when deciding to breed any animals is the overpopulation of pets in general.  Some others include the extra expense, health considerations of your animals, and having to find homes for young rabbits you cannot keep. </p>
            <p>However, if you are an experienced rabbit raiser (or you are a beginner with help), have sound knowledge of rabbit care and health, and want to produce rabbits for showing, meat, or fiber, then it could be an excellent decision to start a breeding program, or at least try it out!  This article contains information to provide you enough knowledge to have a successful start in raising your own rabbits. </p>
        </div>
        <div class="table__container">
            <h3 class="table__container-title list-title">Picking the Right Pair</h3>
            <p>It is advisable to breed only purebred, pedigreed rabbits. The main reason for this is because pedigreed rabbits have documented bloodlines, characteristics, and a general history you can look back on that will help you better predict the outcome of the breeding you have planned.  When breeding two rabbits of unknown heritage, there is a much bigger potential for birthing problems and genetic defects. It is also easier to find homes and interested buyers for well-bred stock. Be advised though, that even having two purebred, pedigreed rabbits does not ensure a good cross – the goal should always be for the animals to out-produce themselves. The hope is that the offspring will be of better quality and meet the ideal of the breed standard more closely than their parents.  Therefore, you must carefully evaluate your pairing to make sure the rabbits complement one another in confirmation (body type) and if it matters to the breed, color and markings as well. </p>
            <p>Another wise thing to do when just starting out is to contact a breeder that raises your chosen breed, and offer to purchase a pregnant doe from him or her.  Ask to have her bred to one of the breeder’s best bucks, although with an increase in quality comes an increase in price.  It can be a great investment though, and get you started with young rabbits you know were bred well. </p>
        </div>
        <div class="table__container">
            <h3 class="table__container-title list-title">Age for Breeding</h3>
            <p>There is a reason for the expression, “breeds like a rabbit!”  Rabbits are notoriously fertile from a young age, and easy to breed. Their young grow quickly, and the mothers and young do not require a lot of human intervention, for the most part.  However, in order to ensure the health of your animals, it is prudent to wait until they reach full body and reproductive maturity before breeding. There are four main weight classes of rabbits:  small, medium, large, and giant breeds. The age at which the rabbit is ready to reproduce depends highly on the maximum weight they are expected to achieve as an adult.  Smaller breeds tend to sexually mature faster than the larger breeds.  The general rule for the proper age to begin breeding at is as follows:</p>
            <ul class="table__ul-lists">
                <li class="table__ul-lists-item">Small breeds (under 6 pounds max) – 4  ½ months</li>
                <li class="table__ul-lists-item">Medium to Large Breeds (6-11 pounds max) – 6 months</li>
                <li class="table__ul-lists-item">Giant Breeds (Over 11 pounds max) – 9 months</li>
            </ul>
            <p>Also in general, bucks tend to be about a month behind does in maturing. So, if you want to mate a purebred Polish buck and doe, she might be ready at 4 ½ months of age to reproduce, but it would be advisable to wait until he is closer to 6 months of age.  Waiting is worth it – your animals will be much more productive, or perhaps “reproductive,” if you are patient and wait until they’re really ready!</p>
        </div>
        <div class="table__container">
            <h3 class="table__container-title list-title">Mating</h3>
            <p>Most often, rabbit mating is a quick and painless process, requiring little to no assistance on the part of their human handlers.  When you are ready to have the doe bred, the most important thing to remember is to bring the doe to the buck’s cage – NOT the other way around.  Sexually mature does are incredibly territorial, and can do severe damage to a buck that suddenly enters her territory.  It only helps to have good equipment.  A wire cage, such as our Supreme Rabbit Cages, that open from the front and are all wire allow for easy access and easy monitoring.  Most often, once the doe is placed in the cage housing the buck, he will circle her briefly, and then mount her.  If she is receptive, she will lift her tail for him.  A really good sign is when the buck gives a grunt when he’s done doing his thing, and falls off of the doe onto his side.  Once this has occurred, it is wise to get the doe out of there.  Although some bucks are more aggressive than others, they will rarely hurt the doe.  If you do not see the ritual just described take place within a minute or so of placing them together, and it looks like they are getting along, you can leave the doe in there for a few minutes to see what will happen.  If you’re not sure if the mating was successful, it is a good idea to try again anywhere from 6 to 10 hours later, and simply repeat what you did the first time.  If you are unsure about whether or not a successful breeding took place, you can carefully introduce the doe to the buck again in about 7-10 days.  If she is uninterested in him, or acts grouchy, she is probably pregnant. </p>
        </div>
        <div class="table__container">
            <h3 class="table__container-title list-title">Palpating</h3>
            <p>It can be frustrating to find that you waited nearly an entire month, and your female rabbit was never pregnant!  You can avoid some of this wait time by palpating your doe 10-14 days after mating to see if you can feel any babies.  Learning to palpate takes a little practice. Older does are easier to practice on than first litter does, as their muscles are a bit more relaxed, and they are generally more patient. Take the doe out of her cage and place her on a carpeted table.  With one hand, grasp the doe over the shoulders and take the other hand with the thumb and fingers opposing each other push up into the abdomen just in front of the pelvis. This can feel awkward at first, and most people don’t want to push hard enough to actually feel anything.  Enough pressure can be used to raise the doe's hindquarters nearly off the table. People who fail at palpation usually do so out of fear of hurting the doe her babies. The chances of that happening are very slim. Each embryo is cushioned in its own amniotic sac, so what you are actually feeling is the fluid filled amnion-not the embryo itself. Once you are secure in your position, move your hand back and forth along each side of the abdomen and slightly towards the middle.  At 10 days, the embryo feels like a firm blueberry.  At 12 days, they feel more like marbles, and at 14 days, they should feel more like large grapes or olives. Once you feel an embryo or two, it is wise to stop and pet the doe, and let her go back to her home.  The entire procedure takes only seconds to perform once you know how.  A common palpation mistake occurs when people confuse the round fecal pellets for embryos. Confusion can be avoided by remembering that the fecal pellets are small, very hard, and are found closer to the backbone, while embryos are found about midway into the abdominal cavity. If you squeeze these pellets instead of embryos, they will feel very hard, almost like rocks.  Developing babies have more of a firm-fruit feel.</p>
        </div>
        <div class="table__container">
            <h3 class="table__container-title list-title">Nesting and Kindling</h3>
            <p>Gestation in rabbits is typically 28-34 days.  However, many breeders will tell you that their rabbits nearly always kindle (give birth) on the 31st day!  Around day 26, you should place a nest box in the doe’s cage so that she can begin to prepare a nest.  You can provide a wooden nest box, or a metal one that is easy to clean and sanitize, such as the Rabbit Metal Nest Boxes we carry.  They come in a variety of sizes, and it is important to get the right size for the breed of rabbit you have.  The rule of thumb is that it only needs to be large enough for the doe to comfortably turn her body around in.  The idea is that it is a cozy den for the babies to stay warm and dry.   If the nest box is too large, it may also lead the female to start using it as a toilet, which is not healthy for her litter.  The nest box should be filled with wood shavings, and plenty of fresh grass hay.  The doe will instinctively begin to pull fur from her chest and back to line the nest she is preparing for her babies.  Some does pull hair a bit gradually, and some wait until right before they kindle. </p>
            <p>It is important, during these last few days, that the doe have ample access to fresh hay and water, along with her regular pellet feed.  It is also important to keep her environment free from unusual or sudden loud noises, as this can spook the doe, and cause her to stomp on or even eat her kits (babies) at birth. </p>
            <p>At least once a day, look carefully at the nest box.  There is no need to disturb it, or pull it out to look at it.  You are looking for movement.  Most rabbits kindle late at night, or in the early hours of the morning.  You will know that the babies have arrived, when you see the fluff in the nest box moving, seemingly on its own!  There are varying opinions around when the nest box should be pulled out and looked at.  Ideally, this should be done in the first 24 hours, to check on the health and well being of the newborns.  Any dead kits, or remaining placenta should be removed immediately and disposed of.  A sign of a successful, healthy delivery is little to no trace of blood, and kits that appear to be clean, dry, and have big round bellies.  The young are very vulnerable, as they are born naked, blind, and deaf.  It is okay to handle each kit gently, as the mother rabbit is likely used to your scent.  Also, rabbits only nurse their young twice a day, for 5-10 minutes at a time, so don’t interrupt if you see that happening!</p>
        </div>
    </div>

    <?php include('partials/footer.php'); ?>